sudo: required

services:
  - docker

before_install:

  - docker build -t "$DOCKER_ID"/react-client-test -f ./client/Dockerfile.dev ./client
script:
  - docker run "$DOCKER_ID"/react-client-test npm test -- --coverage

after_success:
  - docker build -t "$DOCKER_ID"/multi-client ./client
  - docker build -t "$DOCKER_ID"/multi-nginx -f ./nginx/Dockerfile.dev ./nginx
  - docker build -t "$DOCKER_ID"/multi-server ./server
  - docker build -t "$DOCKER_ID"/multi-worker ./worker
  
  # Login into docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # push images to docker hub
  - docker push "$DOCKER_ID"/multi-client
  - docker push "$DOCKER_ID"/multi-nginx
  - docker push "$DOCKER_ID"/multi-server
  - docker push "$DOCKER_ID"/multi-worker
